server:
  port: 8080



spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            allowedOrigins:
              - "http://localhost:5173"



      discovery:
        locator:
          enabled: true

      routes:

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**


        - id: ticket-service
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/ticket-service/**



        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**


        - id: train-service
          uri: lb://train-service
          predicates:
            - Path=/train-service/**

        - id: station-service
          uri: lb://station-service
          predicates:
            - Path=/station-service/**

  output:
    ansi:
      enabled: ALWAYS


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"



springdoc:
  swagger-ui:
    url: /swagger-ui.html
  api-docs:
    path: /v3/api-docs




#Here you can use circuitbreaker for fault tolerance


